from typing import Protocol, runtime_checkable, Optional, Dict, List, TYPE_CHECKING
if TYPE_CHECKING:
    from onelogin.saml2.settings import OneLogin_Saml2_Settings

@runtime_checkable
class _SamlAuthProto(Protocol):
    # Core
    def login(self, *args, **kwargs) -> str: ...
    def process_response(self) -> None: ...
    def is_authenticated(self) -> bool: ...
    def logout(self, *args, **kwargs) -> str: ...


    # Assertions / session
    def get_attributes(self) -> dict: ...
    def get_nameid(self) -> Optional[str]: ...
    def get_session_index(self) -> Optional[str]: ...


    # Extra info
    def get_settings(self) -> "OneLogin_Saml2_Settings": ...
    def get_issuer(self) -> Optional[str]: ...
    def get_authn_context(self) -> Optional[str]: ...


    # Errors
    def get_errors(self) -> list[str]: ...
    def get_last_error_reason(self) -> Optional[str]: ...


    # Optional extra getters (only if you decide to use them)
    def get_last_assertion_not_on_or_after(self) -> Optional[int]: ...
    def get_session_expiration(self) -> Optional[int]: ...