[project]
name = "entra-protocol-lab"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "Flask==3.0.3",
  "Authlib==1.3.1",
  "python3-saml==1.16.0",
  "requests>=2.32,<3",
  "Flask-Session>=0.5.0,<0.7",
  "python-dotenv>=1.0.1,<2",
]